<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <StartupObject>Dolly.Desktop.Program</StartupObject>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
      <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="WPF-UI" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controls\" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Layout\ProductOverviewView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Layout\ProductsPaneView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\RelatedProductsWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Views\Layout\ProductImageView.xaml~">
        <DependentUpon>ProductImageView.xaml</DependentUpon>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dolly.Application\Dolly.Application.csproj" />
      <ProjectReference Include="..\Dolly.Infrastructure\Dolly.Infrastructure.csproj" />
    </ItemGroup>

</Project>
